### ISSUE TITLE
Error while update

### ISSUE THREAD

**Issue by FroZenMember** [Danielv123/factorioClusterio#122] opened 2018-07-01 14:37 UTC
While updating the server with the integrated function there came up an error on step 3:

fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.<anonymous> (C:\Users\FroZenSteel\Desktop\Clustorio-Keks\factorioClusterio\client.js:32:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by Danielv123** [comment] 2018-07-09 08:05
this is caused by a mistake in the defaults, can be fixed by copying the new config. Jason.dist

**Closed** 2018-07-28 10:58 UTC
