### ISSUE TITLE
Master page not loading., Server 2012 r2

### ISSUE THREAD

**Issue by EurypteriD192** [Danielv123/factorioClusterio#104] opened 2018-05-26 07:17 UTC
Followed the install procedure, its able to send data between servers and so . 
but the master:8080 does not list the clients or the content of the server. 

Deleted, and recreated fully same issue. 
If you want i can via discord or so share screen so you can see configs or if something is set up wrong.

**Comment by Danielv123** [comment] 2018-05-26 09:28
Since the backend works, this sounds like a browser issue. Have you tried with Chrome 66? That is what I use for development. Screenshots of the site + browser console would also be nice.

**Comment by EurypteriD192** [comment] 2018-05-26 09:59
I have used chrome 66, IE, egde and firefox.

**Comment by Danielv123** [comment] 2018-05-26 10:51
Slaves txt files should be empty. The database/items.json should not be empty after you have put in items and restarted the master once.

Is the inventory combinator working?

**Comment by EurypteriD192** [comment] 2018-05-26 10:57
By inventory combinator you mean ability send resources betwseen servers ? I can see the research is working across

**Comment by Danielv123** [comment] 2018-05-26 10:58
By the inventory combinator I mean the entity that show the items in the cloud. Do item teleports work *at all*?

Could you share the master IP + access token so I can grab some metrics?

**Comment by EurypteriD192** [comment] 2018-05-26 11:05
Sure but  can you ping me via discord or something as i rather not have it up here :P discord is Tjalmann#9073

Just tested inventory is shared across servers. got 2 test servers running atm

**Comment by Danielv123** [comment] 2018-05-26 12:13
Sent you discord PM

**Comment by EurypteriD192** [comment] 2018-05-26 12:18
Have not gotten anything 

But checked the web interface as you mentionedo n reddit. And there is bunch of errors showing up.

**Comment by Danielv123** [comment] 2018-05-26 12:28
I need to know WHAT errors.

**Comment by EurypteriD192** [comment] 2018-05-26 12:28
GET http://192.168.0.33:8080/external/moment.min.js 404 (Not Found)
nodes:1 Refused to execute script from 'http://192.168.0.33:8080/external/moment.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
nodes:1 Refused to apply style from 'http://192.168.0.33:8080/external/css/Roboto.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
nodes:9 GET http://192.168.0.33:8080/external/mousetrap.min.js 404 (Not Found)
nodes:1 Refused to execute script from 'http://192.168.0.33:8080/external/mousetrap.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
main.js:166 Uncaught ReferenceError: $ is not defined
    at main.js:166
(anonymous) @ main.js:166
nodes:1 Refused to apply style from 'http://192.168.0.33:8080/external/css/Roboto.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
slaveDisplay.js:14 Uncaught ReferenceError: moment is not defined
    at XMLHttpRequest.xmlhttp.onreadystatechange (slaveDisplay.js:14)

**Comment by Danielv123** [comment] 2018-05-26 12:56
Apparently you have some security settings enabled that I don't have. This should be fixed on the clusterio side in master.js

Thanks for the report,

**Comment by EurypteriD192** [comment] 2018-05-26 12:57
Ah. Any other logs or so i can provide you?

**Comment by Danielv123** [comment] 2018-05-26 13:12
Not a bug. Can be fixed by `node ./lib/npmPostinstall.js`

If the command fails, manually download these files to these locations:

```Downloaded static/pictures/spritesheet.js from http://fbpviewer.trakos.pl/images/spritesheet.json
Downloaded static/pictures/spritesheet.png from http://fbpviewer.trakos.pl/images/spritesheet.png
Downloaded static/external/jquery.js from https://code.jquery.com/jquery.js
Downloaded static/external/jquery-ui.js from https://code.jquery.com/ui/1.12.1/jquery-ui.js
Downloaded static/external/canvasjs.js from https://cdnjs.cloudflare.com/ajax/libs/canvasjs/1.7.0/canvasjs.js
Downloaded static/external/moment.min.js from https://momentjs.com/downloads/moment.min.js
Downloaded static/external/mousetrap.min.js from https://craig.global.ssl.fastly.net/js/mousetrap/mousetrap.min.js
Downloaded static/external/css/Roboto.css from https://fonts.googleapis.com/css?family=Roboto
Downloaded static/external/socket.io.js from https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js```

**Closed by Danielv123** 2018-05-26 13:12 UTC
Labels: bug
